[package]
name = "serde-java-properties"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Xiphoseer/serde-java-properties"

[dependencies]
serde = { version = "1", features = ["derive"] }
java-properties = "1.4"
encoding = "0.2.33"
